local _, ZF = ...
ZF.DefaultsUnits = ZF.DefaultsUnits or {}

ZF.DefaultsUnits.player = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 244,
                    Height = 42,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    Layout = {"CENTER", "CENTER", -425.1, -275.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "GRADIENT",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    Position = "BOTTOM",
                    BackgroundMultiplier = 0.75,
                },
                SecondaryPowerBar = {
                    Enabled = false,
                    Height = 3,
                    Position = "TOP",
                    ColorByType = true,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                },
                AlternativePowerBar = {
                    Enabled = true,
                    Height = 5,
                    Width = 100,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {34/255, 34/255, 34/255},
                    ColorByType = true,
                    Inverse = false,
                    Layout = {"LEFT", "BOTTOMLEFT", 3, 1},
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {128/255, 128/255, 255/255},
                    Background = {34/255, 34/255, 34/255},
                    NotInterruptibleColor = {255/255, 64/255, 64/255},
                    InterruptedFailedColor = {64/255, 255/255, 64/255},
                    InterruptCooldownColor = {255/255, 210/255, 0/255},
                    MatchParentWidth = true,
                    ColorByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Color = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Color = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 42,
                    Height = 42,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "TOP", 0, 0},
                    },
                    LeaderAssistant = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"TOPLEFT", "TOPLEFT", 3, -3},
                    },
                    Resting = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                        Texture = "RESTING0"
                    },
                    Combat = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"CENTER", "TOP", 0, 0},
                        Texture = "COMBAT0"
                    },
                    PvP = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"RIGHT", "TOPRIGHT", -3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Totems = {
                        Enabled = true,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        GrowthDirection = "LEFT",
                    },
                    Threat = {
                        Enabled = false,
                    },
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    PrivateAuras = {
                        Enabled = false,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1},
                        FrameStrata = "LOW",
                        Size = 48,
                        Spacing = 1,
                        GrowthX = "LEFT",
                        GrowthY = "UP",
                        InitialAnchor = "BOTTOMRIGHT",
                        Num = 4,
                        BorderScale = -1,
                        DisableCooldown = false,
                        DisableCooldownText = false,
                    },
                    Buffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1, 1},
                        Num = 4,
                        Wrap = 4,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 1, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Color = {1, 1, 1},
                        Tag = "[curhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Color = {1, 1, 1},
                        Tag = "[powercolor][curpp]",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.target = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 244,
                    Height = 42,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    Layout = {"CENTER", "CENTER", 425.1, -275.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                    DispelHighlight = {
                        Enabled = true,
                        Style = "GRADIENT",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {128/255, 128/255, 255/255},
                    Background = {34/255, 34/255, 34/255},
                    NotInterruptibleColor = {255/255, 64/255, 64/255},
                    InterruptedFailedColor = {64/255, 255/255, 64/255},
                    InterruptCooldownColor = {255/255, 210/255, 0/255},
                    MatchParentWidth = true,
                    ColorByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Color = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Color = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 42,
                    Height = 42,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "TOP", 0, 0},
                    },
                    LeaderAssistant = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"TOPRIGHT", "TOPRIGHT", -3, -3},
                    },
                    Combat = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"CENTER", "TOP", 0, 0},
                        Texture = "COMBAT0"
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = false,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    },
                    Classification = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Texture = "CLASSIFICATION3",
                    },
                    Quest = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"TOPLEFT", "TOPLEFT", 3, -3},
                        Texture = "DEFAULT",
                    },
                    Threat = {
                        Enabled = false
                    },
                },
                Range = {
                    Enabled = true,
                    InRange = 1.0,
                    OutOfRange = 0.5,
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 1, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1, 1},
                        Num = 4,
                        Wrap = 4,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"LEFT", "LEFT", 3, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Color = {1, 1, 1},
                        Tag = "[curhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Color = {1, 1, 1},
                        Tag = "[powercolor][curpp]",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.targettarget = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    AnchorToFrame = "ZF_Target",
                    Layout = {"TOPRIGHT", "BOTTOMRIGHT", 0, -26.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = false,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.focus = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    AnchorToFrame = "ZF_Player",
                    Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 36.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                    DispelHighlight = {
                        Enabled = false,
                        Style = "GRADIENT",
                    },
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"BOTTOMLEFT", "TOPLEFT", 0, 1},
                    Foreground = {128/255, 128/255, 255/255},
                    Background = {34/255, 34/255, 34/255},
                    NotInterruptibleColor = {255/255, 64/255, 64/255},
                    InterruptedFailedColor = {64/255, 255/255, 64/255},
                    InterruptCooldownColor = {255/255, 210/255, 0/255},
                    MatchParentWidth = true,
                    ColorByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = false,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Color = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Color = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"RIGHT", "TOPRIGHT", -3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = false,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    },
                    Threat = {
                        Enabled = false
                    },
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 1,
                        Wrap = 1,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.focustarget = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    AnchorToFrame = "ZF_Focus",
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = false,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.pet = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 122,
                    Height = 22,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    AnchorToFrame = "ZF_Player",
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -26.1},
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 20,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 20,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = false,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {128/255, 128/255, 255/255},
                    Background = {34/255, 34/255, 34/255},
                    NotInterruptibleColor = {255/255, 64/255, 64/255},
                    InterruptedFailedColor = {64/255, 255/255, 64/255},
                    InterruptCooldownColor = {255/255, 210/255, 0/255},
                    MatchParentWidth = true,
                    ColorByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = false,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Color = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Color = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = false,
                    Width = 22,
                    Height = 22,
                    Layout = {"LEFT", "RIGHT", 1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = false,
                        Size = 16,
                        Layout = {"LEFT", "TOPLEFT", 3, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = false,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    },
                    Threat = {
                        Enabled = false
                    },
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 1,
                        Wrap = 1,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 22,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER",0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
ZF.DefaultsUnits.boss = {
                Enabled = true,
                ForceHideBlizzard = true,
                Frame = {
                    Width = 244,
                    Height = 42,
                    BorderColor = {0/255, 0/255, 0/255},
                    BorderOpacity = 1,
                    BorderThickness = 1,
                    Layout = {"CENTER", "CENTER", 550.1, -0.1, 26},
                    GrowthDirection = "DOWN",
                    FrameStrata = "LOW",
                },
                HealthBar = {
                    ColorByClass = true,
                    ColorBackgroundByClass = false,
                    ColorByReaction = true,
                    ColorWhenTapped = true,
                    Inverse = false,
                    Smooth = false,
                    Foreground = {8/255, 8/255, 8/255},
                    ForegroundOpacity = 0.8,
                    Background = {34/255, 34/255, 34/255},
                    BackgroundOpacity = 1.0,
                },
                HealPrediction = {
                    IncomingHeal = {
                        Enabled = false,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {64/255, 255/255, 64/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                    Absorbs = {
                        Enabled = true,
                        ShowOverAbsorb = false,
                        UseStripedTexture = true,
                        MatchParentHeight = true,
                        Color = {255/255, 204/255, 0/255, 1.0},
                        Position = "LEFT",
                        Height = 40,
                    },
                    HealAbsorbs = {
                        Enabled = true,
                        UseStripedTexture = false,
                        MatchParentHeight = true,
                        Color = {128/255, 64/255, 255/255, 1.0},
                        Position = "RIGHT",
                        Height = 40,
                    },
                },
                PowerBar = {
                    Enabled = false,
                    Height = 3,
                    Foreground = {8/255, 8/255, 8/255},
                    Background = {128/255, 128/255, 128/255},
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    ColorByClass = false,
                    Smooth = true,
                    Inverse = false,
                    BackgroundMultiplier = 0.75,
                },
                CastBar = {
                    Enabled = true,
                    Width = 244,
                    Height = 24,
                    Layout = {"TOPLEFT", "BOTTOMLEFT", 0, -1},
                    Foreground = {128/255, 128/255, 255/255},
                    Background = {34/255, 34/255, 34/255},
                    NotInterruptibleColor = {255/255, 64/255, 64/255},
                    InterruptedFailedColor = {64/255, 255/255, 64/255},
                    InterruptCooldownColor = {255/255, 210/255, 0/255},
                    MatchParentWidth = true,
                    ColorByClass = false,
                    Inverse = false,
                    HoldTime = 0.5,
                    ShowTarget = false,
                    FrameStrata = "MEDIUM",
                    Icon = {
                        Enabled = true,
                        Position = "LEFT",
                    },
                    Text = {
                        SpellName = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"LEFT", "LEFT", 3, 0},
                            Color = {1, 1, 1},
                            MaxChars = 15,
                        },
                        Duration = {
                            Enabled = true,
                            FontSize = 12,
                            Layout = {"RIGHT", "RIGHT", -3, 0},
                            Color = {1, 1, 1},
                        }
                    }
                },
                Portrait = {
                    Enabled = true,
                    Width = 42,
                    Height = 42,
                    Layout = {"RIGHT", "LEFT", -1, 0},
                    Zoom = 0.3,
                    UseClassPortrait = false,
                    Style = "2D",
                },
                Indicators = {
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        Layout = {"CENTER", "TOP", 0, 0},
                    },
                    Mouseover = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        HighlightOpacity = 0.75,
                        BorderThickness = 1,
                        Style = "GRADIENT"
                    },
                    Target = {
                        Enabled = true,
                        Color = {1, 1, 1},
                        BorderThickness = 3,
                        Style = "Border"
                    }
                },
                Auras = {
                    FrameStrata = "LOW",
                    AuraDuration = {
                        Layout = {"CENTER", "CENTER", 0, 0},
                        FontSize = 12,
                        ScaleByIconSize = false,
                    },
                    Buffs = {
                        Enabled = true,
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"LEFT", "RIGHT", 1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "RIGHT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Debuffs = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        OnlyShowPlayer = false,
                        Size = 34,
                        Layout = {"BOTTOMRIGHT", "TOPRIGHT", 0, 1, 1},
                        Num = 4,
                        Wrap = 4,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HARMFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                    Custom = {
						AnchorRegion = "Frame",
                        Enabled = false,
                        Type = "Buffs",
                        OnlyShowPlayer = false,
                        Size = 42,
                        Layout = {"RIGHT", "LEFT", -1, 0, 1},
                        Num = 3,
                        Wrap = 3,
                        GrowthDirection = "LEFT",
                        WrapDirection = "UP",
                        ShowType = false,
                        Blacklist = false,
                        Filter = "HELPFUL",
                        Sorting = "BLIZZARD",
                        Count = {
                            HideStacks = false,
                            Layout = {"BOTTOMRIGHT", "BOTTOMRIGHT", 0, 2},
                            FontSize = 12,
                            Color = {1, 1, 1, 1}
                        }
                    },
                },
                Tags = {
                    TagOne = {
                        FontSize = 12,
                        Layout = {"LEFT", "LEFT", 3, 0},
                        Color = {1, 1, 1},
                        Tag = "[name]",
                    },
                    TagTwo = {
                        FontSize = 12,
                        Layout = {"RIGHT", "RIGHT", -3, 0},
                        Color = {1, 1, 1},
                        Tag = "[curhpperhp:abbr]",
                    },
                    TagThree = {
                        FontSize = 12,
                        Layout = {"RIGHT", "BOTTOMRIGHT", -3, 2},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFour = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                    TagFive = {
                        FontSize = 12,
                        Layout = {"CENTER", "CENTER", 0, 0},
                        Color = {1, 1, 1},
                        Tag = "",
                    },
                }
}
