std = "lua51"

-- WoW addon style leans on long single-line conditionals throughout this
-- codebase (see e.g. Core/Config/GUI.lua) - that's idiomatic here, not a bug,
-- so line-length checking would be pure noise.
max_line_length = false

-- Every file in this addon opens with `local _, ZF = ...` (the shared
-- per-addon namespace table WoW passes to every loaded file) - so ZF itself
-- is always a proper local and never needs declaring below. These are the
-- addon's actual bare globals - the ones read AND written without going
-- through that local:
globals = {
    "ZFG",                -- Core/Globals.lua: the addon's cross-profile global namespace
    "ZFDB",               -- AceDB SavedVariables table (declared in the .toc, written in Core/Core.lua)
    "ZFDebug",            -- Core/Config/Designer.lua: exposed for /run debugging
    "StaticPopupDialogs", -- Blizzard global table; the addon adds its own popup entries into it
    "SlashCmdList",       -- Blizzard global table; the addon registers its own slash commands into it
    -- Addon Compartment click/tooltip callbacks (Core/Core.lua) - must be real
    -- globals, not locals: the .toc's AddonCompartmentFunc/FuncOnEnter/FuncOnLeave
    -- fields tell Blizzard to look these up by name in _G.
    "ZenFrames_OnAddonCompartmentClick",
    "ZenFrames_OnAddonCompartmentEnter",
    "ZenFrames_OnAddonCompartmentLeave",
}

-- The Blizzard/WoW API surface this addon actually calls, read-only.
-- Generated by running luacheck once with no globals declared at all and
-- collecting every "accessing undefined variable" name it reported across
-- Core/ and Elements/ - i.e. this is exactly (and only) what's really used,
-- not a guess. If you add a call to a new Blizzard API, luacheck will flag
-- it as undefined here; add the name below (alphabetically) rather than
-- disabling the check.
read_globals = {
    "LibStub", -- Ace3's library registry - an addon-ecosystem convention, not part of Blizzard's API
    "ACCEPT",
    "AbbreviateLargeNumbers",
    "AbbreviateNumbers",
    "Ambiguate",
    "AnchorUtil",
    "CANCEL",
    "C_AddOns",
    "C_CurveUtil",
    "C_SpecializationInfo",
    "C_Spell",
    "C_SpellBook",
    "C_StringUtil",
    "C_Timer",
    "C_UI",
    "C_UnitAuras",
    "CheckInteractDistance",
    "CopyTable",
    "CreateColor",
    "CreateFrame",
    "CurveConstants",
    "DEAD",
    "DropDownList1",
    "DropDownList2",
    "EXIT_GAME",
    "Enum",
    "GameMenuFrame",
    "GameTooltip",
    "GetBuildInfo",
    "GetInstanceInfo",
    "GetNumGroupMembers",
    "GetNumSpecializations",
    "GetRaidRosterInfo",
    "GetShapeshiftFormID",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetTime",
    "HideUIPanel",
    "InCombatLockdown",
    "IsResting",
    "IsSpellKnown",
    "LOGOUT",
    "LOG_OUT",
    "MACROS",
    "OKAY",
    "PlaySound",
    "RAID_CLASS_COLORS",
    "RETURN_TO_GAME",
    "RegisterStateDriver",
    "RegisterUnitWatch",
    "SHAMAN_TOTEM_PRIORITIES",
    "SOUNDKIT",
    "STANDARD_TEXT_FONT",
    "STANDARD_TOTEM_PRIORITIES",
    "SetPortraitTexture",
    "SetRaidTargetIconTexture",
    "StaticPopup_Show",
    "ToggleDropDownMenu",
    "UIDROPDOWNMENU_OPEN_MENU",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_DisableDropDown",
    "UIDropDownMenu_EnableDropDown",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetText",
    "UIDropDownMenu_SetWidth",
    "UIParent",
    "UUFDB", -- legacy SavedVariables table this addon migrates from on first load (the original Unhalted addon's DB)
    "UnitAffectingCombat",
    "UnitCanAttack",
    "UnitClass",
    "UnitClassBase",
    "UnitExists",
    "UnitFactionGroup",
    "UnitFrame_OnEnter",
    "UnitFrame_OnLeave",
    "UnitGUID",
    "UnitGetTotalAbsorbs",
    "UnitGroupRolesAssigned",
    "UnitHealth",
    "UnitHealthMax",
    "UnitHealthMissing",
    "UnitHealthPercent",
    "UnitInParty",
    "UnitInPartyIsAI",
    "UnitInRaid",
    "UnitInRange",
    "UnitIsConnected",
    "UnitIsDead",
    "UnitIsDeadOrGhost",
    "UnitIsFriend",
    "UnitIsGhost",
    "UnitIsPlayer",
    "UnitIsUnit",
    "UnitIsVisible",
    "UnitName",
    "UnitPhaseReason",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerPercent",
    "UnitPowerType",
    "UnitReaction",
    "UnitShouldDisplaySpellTargetName",
    "UnitSpellTargetName",
    "UnregisterStateDriver",
    "UnregisterUnitWatch",
    "WOW_PROJECT_ID",
    "WOW_PROJECT_MAINLINE",
    "date",
    "hooksecurefunc",
    "issecretvalue",
    "strtrim",
    "tremove",
    "wipe",
}

exclude_files = {
    "Libraries/**", -- third-party (oUF, Ace3, LibStub, etc.) - not ours to lint
    ".claude/**",   -- stray tooling/worktree artifacts, not part of the addon
}

-- Deliberately NOT declaring `RefreshSortOrders` above even though it once
-- showed up as "undefined" - that one's a real bug (Core/Config/GUI.lua:670
-- calls it before the `local function RefreshSortOrders` at line 711 is in
-- scope, so it resolves to a nonexistent global instead), not a missing
-- global. Leave it flagged until that's fixed.

-- ignore = { "212", "213" } -- uncomment if unused-callback-argument warnings turn out too noisy
